### PR TITLE
Enable building on non-x86 architectures

### PR DESCRIPTION
**Pull request by mr-c**
Hello again. This is a patch from the Debian package for kalign. It enables building kalign on no-x86 systems using the [SIMD Everywhere](https://github.com/simd-everywhere/simde) header only library.

### CODE REVIEW

**Comment by mr-c** [comment]
The Debian package also removes the call to `m4/ax_ext.m4` in `configure.ac`, but I presume that you'd prefer a switch that defaults to adding the best flags for local compilation instead of its removal.

Instead, on x86 we [compile the kalign binary for each SIMD level](https://salsa.debian.org/med-team/kalign/-/blob/master/debian/rules#L24) and install a [dispatching script](https://salsa.debian.org/med-team/kalign/-/blob/master/debian/bin/simd-dispatch) that picks the best binary at runtime.

**Comment by mr-c** [comment]
@TimoLassmann I've refreshed this PR

**Comment by TimoLassmann** [comment]
Hi,

The latest release of kalign (3.3.2) compiles on M1 and therefore should also compile on other non-x84 systems.

**Comment by TimoLassmann** [comment]
Hi, I think I encapsulated add these platform specific headers in pre-processor statements (`#ifdef HAVE_AVX2`). Therefore I _think_ kalign should compile using standard C headers on all platforms lacking the specific SIMD instructions. Let me know if that is not the case!

**Comment by mr-c** [comment]
Thanks @TimoLassmann ; we have kalign 3.3.4 building on a variety of non-x86 architectures in Debian https://buildd.debian.org/status/package.php?p=kalign

**Comment by TimoLassmann** [comment]
Good to hear, and thanks for you work in putting the debian package together!

**Pull request closed without merging**
